import { NextRequest, NextResponse } from "next/server";
import { createSupabaseServerClient } from "@/lib/supabase/server";

// POST /api/documents/templates/seed — Seed default templates
export async function POST(_req: NextRequest) {
  const supabase = await createSupabaseServerClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const { data: profile } = await supabase
    .from("profiles")
    .select("org_id")
    .eq("id", user.id)
    .single();
  
  if (!profile?.org_id) {
    return NextResponse.json({ error: "Organization not found" }, { status: 404 });
  }

  const orgId = profile.org_id;

  // Check if templates already exist
  const { data: existing } = await supabase
    .from("document_templates")
    .select("id")
    .eq("org_id", orgId)
    .eq("is_default", true);

  if (existing && existing.length > 0) {
    return NextResponse.json({ 
      message: "Default templates already exist", 
      count: existing.length 
    });
  }

  // Default templates data
  const defaultTemplates = [
    {
      org_id: orgId,
      name: "Product Plan",
      type: "product_plan",
      description: "Template untuk membuat rencana produk bisnis",
      html_template: `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>{{product_name}} - Product Plan</title>
  <style>{{css_styles}}</style>
</head>
<body>
  <div class="container">
    <header class="header">
      <div class="logo">{{company_name}}</div>
      <h1>{{product_name}}</h1>
      <p class="subtitle">Product Plan & Strategy</p>
    </header>
    
    <section class="overview">
      <h2>Overview</h2>
      <p>{{overview}}</p>
    </section>
    
    <section class="features">
      <h2>Key Features</h2>
      <div class="feature-grid">
        {{#features}}
        <div class="feature-card">
          <h3>{{name}}</h3>
          <p>{{description}}</p>
        </div>
        {{/features}}
      </div>
    </section>
    
    <section class="timeline">
      <h2>Timeline</h2>
      <div class="timeline-list">
        {{#timeline}}
        <div class="timeline-item">
          <span class="date">{{date}}</span>
          <span class="milestone">{{milestone}}</span>
        </div>
        {{/timeline}}
      </div>
    </section>
    
    <section class="pricing">
      <h2>Pricing</h2>
      <div class="price-tag">Rp {{price}}</div>
      <p>{{pricing_notes}}</p>
    </section>
    
    <footer class="footer">
      <p>Generated by PelangganPro</p>
    </footer>
  </div>
</body>
</html>`,
      css_styles: `.container { max-width: 800px; margin: 0 auto; padding: 40px; font-family: "Inter", -apple-system, sans-serif; color: #1e293b; }
.header { text-align: center; margin-bottom: 40px; border-bottom: 3px solid #3b82f6; padding-bottom: 30px; }
.logo { font-size: 14px; color: #64748b; margin-bottom: 10px; }
.header h1 { font-size: 32px; color: #1e293b; margin: 0; }
.subtitle { font-size: 18px; color: #64748b; margin-top: 8px; }
section { margin-bottom: 30px; }
h2 { font-size: 20px; color: #3b82f6; border-left: 4px solid #3b82f6; padding-left: 12px; margin-bottom: 16px; }
.overview p { line-height: 1.6; font-size: 14px; }
.feature-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 16px; }
.feature-card { background: #f8fafc; padding: 16px; border-radius: 8px; border: 1px solid #e2e8f0; }
.feature-card h3 { font-size: 14px; margin: 0 0 8px 0; color: #1e293b; }
.feature-card p { font-size: 12px; color: #64748b; margin: 0; }
.timeline-list { display: flex; flex-direction: column; gap: 12px; }
.timeline-item { display: flex; align-items: center; padding: 12px; background: #f1f5f9; border-radius: 6px; }
.timeline-item .date { font-weight: 600; color: #3b82f6; min-width: 100px; }
.timeline-item .milestone { color: #475569; }
.pricing { text-align: center; padding: 24px; background: linear-gradient(135deg, #eff6ff 0%, #dbeafe 100%); border-radius: 12px; }
.price-tag { font-size: 36px; font-weight: 700; color: #3b82f6; margin: 16px 0; }
.footer { margin-top: 40px; text-align: center; font-size: 12px; color: #94a3b8; border-top: 1px solid #e2e8f0; padding-top: 20px; }`,
      form_schema: {
        fields: [
          { name: "company_name", label: "Nama Perusahaan", type: "text", required: true },
          { name: "product_name", label: "Nama Produk", type: "text", required: true },
          { name: "overview", label: "Overview Produk", type: "textarea", required: true },
          { name: "features", label: "Fitur", type: "repeater", fields: [
            { name: "name", label: "Nama Fitur", type: "text", required: true },
            { name: "description", label: "Deskripsi", type: "textarea", required: true }
          ]},
          { name: "timeline", label: "Timeline", type: "repeater", fields: [
            { name: "date", label: "Tanggal", type: "text", required: true },
            { name: "milestone", label: "Milestone", type: "text", required: true }
          ]},
          { name: "price", label: "Harga", type: "number", required: true },
          { name: "pricing_notes", label: "Catatan Harga", type: "textarea", required: false }
        ]
      },
      is_default: true,
      is_active: true,
      created_by: user.id,
    },
    {
      org_id: orgId,
      name: "Surat Penawaran",
      type: "penawaran",
      description: "Template surat penawaran resmi",
      html_template: `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Surat Penawaran - {{no_surat}}</title>
  <style>{{css_styles}}</style>
</head>
<body>
  <div class="container">
    <header class="letterhead">
      <div class="company-info">
        <h2>{{company_name}}</h2>
        <p>{{company_address}}</p>
        <p>Telp: {{company_phone}} | Email: {{company_email}}</p>
      </div>
    </header>
    
    <div class="meta">
      <table>
        <tr><td>Nomor</td><td>: {{no_surat}}</td></tr>
        <tr><td>Tanggal</td><td>: {{tanggal}}</td></tr>
        <tr><td>Perihal</td><td>: {{perihal}}</td></tr>
      </table>
    </div>
    
    <div class="recipient">
      <p>Kepada Yth.</p>
      <p><strong>{{recipient_name}}</strong></p>
      <p>{{recipient_address}}</p>
    </div>
    
    <div class="content">
      <p>Dengan hormat,</p>
      <p>{{opening}}</p>
      
      <table class="detail-table">
        <thead>
          <tr>
            <th>No</th>
            <th>Deskripsi</th>
            <th>Jumlah</th>
            <th>Harga</th>
            <th>Total</th>
          </tr>
        </thead>
        <tbody>
          {{#items}}
          <tr>
            <td>{{no}}</td>
            <td>{{deskripsi}}</td>
            <td>{{jumlah}}</td>
            <td>Rp {{harga}}</td>
            <td>Rp {{total}}</td>
          </tr>
          {{/items}}
        </tbody>
        <tfoot>
          <tr>
            <td colspan="4" class="text-right"><strong>Total</strong></td>
            <td><strong>Rp {{grand_total}}</strong></td>
          </tr>
        </tfoot>
      </table>
      
      <p>{{terms}}</p>
      <p>{{closing}}</p>
    </div>
    
    <div class="signature">
      <p>Hormat kami,</p>
      <br><br><br>
      <p><strong>{{sender_name}}</strong></p>
      <p>{{sender_title}}</p>
    </div>
  </div>
</body>
</html>`,
      css_styles: `.container { max-width: 800px; margin: 0 auto; padding: 60px; font-family: "Times New Roman", serif; font-size: 12pt; line-height: 1.6; color: #000; }
.letterhead { text-align: center; border-bottom: 2px solid #000; padding-bottom: 20px; margin-bottom: 30px; }
.letterhead h2 { margin: 0 0 10px 0; font-size: 16pt; }
.letterhead p { margin: 4px 0; font-size: 10pt; }
.meta { margin-bottom: 30px; }
.meta table { border-collapse: collapse; }
.meta td { padding: 2px 8px 2px 0; font-size: 11pt; }
.recipient { margin-bottom: 30px; }
.recipient p { margin: 4px 0; }
.content p { margin: 12px 0; text-align: justify; }
.detail-table { width: 100%; border-collapse: collapse; margin: 20px 0; }
.detail-table th, .detail-table td { border: 1px solid #000; padding: 8px; text-align: left; font-size: 11pt; }
.detail-table th { background: #f0f0f0; }
.detail-table tfoot td { border-top: 2px solid #000; }
.text-right { text-align: right; }
.signature { margin-top: 60px; text-align: right; }
.signature p { margin: 4px 0; }`,
      form_schema: {
        fields: [
          { name: "company_name", label: "Nama Perusahaan", type: "text", required: true },
          { name: "company_address", label: "Alamat Perusahaan", type: "textarea", required: true },
          { name: "company_phone", label: "Telepon", type: "text", required: true },
          { name: "company_email", label: "Email", type: "text", required: true },
          { name: "no_surat", label: "Nomor Surat", type: "text", required: true },
          { name: "tanggal", label: "Tanggal", type: "date", required: true },
          { name: "perihal", label: "Perihal", type: "text", required: true },
          { name: "recipient_name", label: "Nama Penerima", type: "text", required: true },
          { name: "recipient_address", label: "Alamat Penerima", type: "textarea", required: true },
          { name: "opening", label: "Pembukaan", type: "textarea", required: true },
          { name: "items", label: "Item Penawaran", type: "repeater", fields: [
            { name: "no", label: "No", type: "text", required: true },
            { name: "deskripsi", label: "Deskripsi", type: "text", required: true },
            { name: "jumlah", label: "Jumlah", type: "number", required: true },
            { name: "harga", label: "Harga Satuan", type: "number", required: true },
            { name: "total", label: "Total", type: "number", required: true }
          ]},
          { name: "grand_total", label: "Grand Total", type: "number", required: true },
          { name: "terms", label: "Syarat & Ketentuan", type: "textarea", required: true },
          { name: "closing", label: "Penutup", type: "textarea", required: true },
          { name: "sender_name", label: "Nama Pengirim", type: "text", required: true },
          { name: "sender_title", label: "Jabatan", type: "text", required: true }
        ]
      },
      is_default: true,
      is_active: true,
      created_by: user.id,
    },
    {
      org_id: orgId,
      name: "Invoice",
      type: "invoice",
      description: "Template invoice profesional",
      html_template: `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Invoice {{invoice_number}}</title>
  <style>{{css_styles}}</style>
</head>
<body>
  <div class="container">
    <header class="invoice-header">
      <div class="brand">
        <h1>INVOICE</h1>
        <div class="invoice-number">#{{invoice_number}}</div>
      </div>
      <div class="company">
        <strong>{{company_name}}</strong>
        <p>{{company_address}}</p>
        <p>{{company_phone}} | {{company_email}}</p>
      </div>
    </header>
    
    <div class="invoice-meta">
      <div class="client-info">
        <label>Invoice To:</label>
        <strong>{{client_name}}</strong>
        <p>{{client_address}}</p>
      </div>
      <div class="dates">
        <div><label>Invoice Date:</label> <span>{{invoice_date}}</span></div>
        <div><label>Due Date:</label> <span>{{due_date}}</span></div>
      </div>
    </div>
    
    <table class="items-table">
      <thead>
        <tr>
          <th>#</th>
          <th>Description</th>
          <th>Qty</th>
          <th>Price</th>
          <th>Amount</th>
        </tr>
      </thead>
      <tbody>
        {{#items}}
        <tr>
          <td>{{no}}</td>
          <td>{{description}}</td>
          <td>{{qty}}</td>
          <td>Rp {{price}}</td>
          <td>Rp {{amount}}</td>
        </tr>
        {{/items}}
      </tbody>
    </table>
    
    <div class="summary">
      <div class="summary-row">
        <span>Subtotal:</span>
        <span>Rp {{subtotal}}</span>
      </div>
      <div class="summary-row">
        <span>PPN ({{tax_percent}}%):</span>
        <span>Rp {{tax_amount}}</span>
      </div>
      <div class="summary-row total">
        <span>Total:</span>
        <span>Rp {{total}}</span>
      </div>
    </div>
    
    <div class="payment-info">
      <h3>Payment Information</h3>
      <p><strong>Bank:</strong> {{bank_name}}</p>
      <p><strong>Account:</strong> {{bank_account}}</p>
      <p><strong>Account Name:</strong> {{bank_account_name}}</p>
    </div>
    
    <footer class="invoice-footer">
      <p>Thank you for your business!</p>
    </footer>
  </div>
</body>
</html>`,
      css_styles: `.container { max-width: 800px; margin: 0 auto; padding: 40px; font-family: "Inter", -apple-system, sans-serif; background: #fff; }
.invoice-header { display: flex; justify-content: space-between; margin-bottom: 40px; padding-bottom: 20px; border-bottom: 3px solid #3b82f6; }
.brand h1 { font-size: 36px; color: #3b82f6; margin: 0; }
.invoice-number { font-size: 18px; color: #64748b; margin-top: 8px; }
.company { text-align: right; }
.company strong { display: block; font-size: 16px; margin-bottom: 8px; }
.company p { margin: 4px 0; font-size: 12px; color: #64748b; }
.invoice-meta { display: flex; justify-content: space-between; margin-bottom: 40px; }
.client-info label { display: block; font-size: 11px; color: #64748b; text-transform: uppercase; margin-bottom: 8px; }
.client-info strong { display: block; font-size: 16px; margin-bottom: 4px; }
.client-info p { margin: 4px 0; font-size: 12px; color: #475569; }
.dates label { font-size: 11px; color: #64748b; text-transform: uppercase; display: inline-block; width: 100px; }
.dates span { font-weight: 500; }
.items-table { width: 100%; border-collapse: collapse; margin-bottom: 30px; }
.items-table th { background: #3b82f6; color: #fff; padding: 12px; text-align: left; font-size: 12px; text-transform: uppercase; }
.items-table td { padding: 12px; border-bottom: 1px solid #e2e8f0; font-size: 13px; }
.items-table tr:last-child td { border-bottom: 2px solid #3b82f6; }
.summary { width: 300px; margin-left: auto; margin-bottom: 40px; }
.summary-row { display: flex; justify-content: space-between; padding: 8px 0; font-size: 13px; color: #64748b; }
.summary-row.total { font-size: 18px; font-weight: 700; color: #1e293b; border-top: 2px solid #3b82f6; margin-top: 8px; padding-top: 12px; }
.payment-info { background: #f8fafc; padding: 20px; border-radius: 8px; margin-bottom: 40px; }
.payment-info h3 { margin: 0 0 12px 0; font-size: 14px; color: #1e293b; }
.payment-info p { margin: 4px 0; font-size: 13px; color: #475569; }
.invoice-footer { text-align: center; padding-top: 30px; border-top: 1px solid #e2e8f0; }
.invoice-footer p { color: #64748b; font-size: 13px; }`,
      form_schema: {
        fields: [
          { name: "company_name", label: "Nama Perusahaan", type: "text", required: true },
          { name: "company_address", label: "Alamat", type: "textarea", required: true },
          { name: "company_phone", label: "Telepon", type: "text", required: true },
          { name: "company_email", label: "Email", type: "text", required: true },
          { name: "invoice_number", label: "Nomor Invoice", type: "text", required: true },
          { name: "invoice_date", label: "Tanggal Invoice", type: "date", required: true },
          { name: "due_date", label: "Jatuh Tempo", type: "date", required: true },
          { name: "client_name", label: "Nama Klien", type: "text", required: true },
          { name: "client_address", label: "Alamat Klien", type: "textarea", required: true },
          { name: "items", label: "Items", type: "repeater", fields: [
            { name: "no", label: "No", type: "text", required: true },
            { name: "description", label: "Deskripsi", type: "text", required: true },
            { name: "qty", label: "Qty", type: "number", required: true },
            { name: "price", label: "Harga", type: "number", required: true },
            { name: "amount", label: "Jumlah", type: "number", required: true }
          ]},
          { name: "subtotal", label: "Subtotal", type: "number", required: true },
          { name: "tax_percent", label: "PPN %", type: "number", required: true },
          { name: "tax_amount", label: "Jumlah PPN", type: "number", required: true },
          { name: "total", label: "Total", type: "number", required: true },
          { name: "bank_name", label: "Nama Bank", type: "text", required: true },
          { name: "bank_account", label: "Nomor Rekening", type: "text", required: true },
          { name: "bank_account_name", label: "Nama Rekening", type: "text", required: true }
        ]
      },
      is_default: true,
      is_active: true,
      created_by: user.id,
    },
    {
      org_id: orgId,
      name: "Struk Kasir",
      type: "struk",
      description: "Template struk belanja thermal style",
      html_template: `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Struk {{transaction_id}}</title>
  <style>{{css_styles}}</style>
</head>
<body>
  <div class="receipt">
    <header class="receipt-header">
      <h1>{{store_name}}</h1>
      <p>{{store_address}}</p>
      <p>Telp: {{store_phone}}</p>
    </header>
    
    <div class="divider"></div>
    
    <div class="receipt-info">
      <p>No: {{transaction_id}}</p>
      <p>Tgl: {{date}}</p>
      <p>Kasir: {{cashier}}</p>
    </div>
    
    <div class="divider"></div>
    
    <table class="items">
      <tbody>
        {{#items}}
        <tr>
          <td class="item-name">{{name}}</td>
          <td class="item-qty">{{qty}}x</td>
          <td class="item-price">Rp {{price}}</td>
          <td class="item-total">Rp {{total}}</td>
        </tr>
        {{/items}}
      </tbody>
    </table>
    
    <div class="divider"></div>
    
    <div class="totals">
      <div class="total-row">
        <span>Total</span>
        <span>Rp {{grand_total}}</span>
      </div>
      <div class="total-row">
        <span>Tunai</span>
        <span>Rp {{paid}}</span>
      </div>
      <div class="total-row change">
        <span>Kembali</span>
        <span>Rp {{change}}</span>
      </div>
    </div>
    
    <div class="divider"></div>
    
    <footer class="receipt-footer">
      <p>Terima Kasih</p>
      <p>Selamat Belanja Kembali</p>
    </footer>
  </div>
</body>
</html>`,
      css_styles: `.receipt { width: 300px; margin: 0 auto; padding: 20px; font-family: "Courier New", monospace; font-size: 12px; background: #fff; color: #000; }
.receipt-header { text-align: center; margin-bottom: 10px; }
.receipt-header h1 { font-size: 16px; margin: 0 0 5px 0; font-weight: bold; }
.receipt-header p { margin: 2px 0; font-size: 10px; }
.divider { border-top: 1px dashed #000; margin: 10px 0; }
.receipt-info p { margin: 3px 0; font-size: 11px; }
.items { width: 100%; border-collapse: collapse; }
.items td { padding: 3px 0; font-size: 11px; vertical-align: top; }
.item-name { width: 40%; }
.item-qty { width: 15%; text-align: center; }
.item-price { width: 20%; text-align: right; }
.item-total { width: 25%; text-align: right; font-weight: bold; }
.totals { margin: 10px 0; }
.total-row { display: flex; justify-content: space-between; margin: 5px 0; font-size: 12px; }
.total-row.change { font-weight: bold; font-size: 13px; border-top: 1px solid #000; padding-top: 5px; margin-top: 8px; }
.receipt-footer { text-align: center; margin-top: 15px; }
.receipt-footer p { margin: 3px 0; font-size: 11px; }`,
      form_schema: {
        fields: [
          { name: "store_name", label: "Nama Toko", type: "text", required: true },
          { name: "store_address", label: "Alamat Toko", type: "textarea", required: true },
          { name: "store_phone", label: "Telepon", type: "text", required: true },
          { name: "transaction_id", label: "No Transaksi", type: "text", required: true },
          { name: "date", label: "Tanggal", type: "text", required: true },
          { name: "cashier", label: "Kasir", type: "text", required: true },
          { name: "items", label: "Items", type: "repeater", fields: [
            { name: "name", label: "Nama Item", type: "text", required: true },
            { name: "qty", label: "Qty", type: "number", required: true },
            { name: "price", label: "Harga", type: "number", required: true },
            { name: "total", label: "Total", type: "number", required: true }
          ]},
          { name: "grand_total", label: "Grand Total", type: "number", required: true },
          { name: "paid", label: "Bayar", type: "number", required: true },
          { name: "change", label: "Kembali", type: "number", required: true }
        ]
      },
      is_default: true,
      is_active: true,
      created_by: user.id,
    },
  ];

  // Insert templates
  const { data, error } = await supabase
    .from("document_templates")
    .insert(defaultTemplates)
    .select();

  if (error) {
    console.error("[Seed Templates] Error:", error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }

  return NextResponse.json({
    message: "Default templates created successfully",
    count: data?.length || 0,
    templates: data,
  });
}
